"""add preferred_language to users

Revision ID: 10185a74f2e7
Revises: b90ef853a23b
Create Date: 2026-04-15 07:59:50.603343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10185a74f2e7'
down_revision: Union[str, None] = 'b90ef853a23b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column but allow it to be empty temporarily
    op.add_column('applications', sa.Column('preferred_language', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=5), nullable=True))
    
    # 2. Give existing records a default language
    op.execute("UPDATE applications SET preferred_language = 'en' WHERE preferred_language IS NULL")
    op.execute("UPDATE users SET preferred_language = 'en' WHERE preferred_language IS NULL")
    
    # 3. Enforce the strict non-nullable requirement
    op.alter_column('applications', 'preferred_language', nullable=False)
    op.alter_column('users', 'preferred_language', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('applications', 'preferred_language')
    # ### end Alembic commands ###