"""Update participant roles, stats, and add array fields

Revision ID: 1d835b96fe09
Revises: 92d0246ea752
Create Date: 2026-04-07 20:33:07.071319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d835b96fe09'
down_revision: Union[str, None] = '92d0246ea752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column but allow it to be empty temporarily
    op.add_column('applications', sa.Column('country', sa.String(), nullable=True))
    
    # 2. Give all existing applications a default country
    op.execute("UPDATE applications SET country = 'Ghana' WHERE country IS NULL")
    
    # 3. Now enforce the strict requirement so future applications must have a country
    op.alter_column('applications', 'country', nullable=False)

    op.add_column('applications', sa.Column('sporting_disciplines', postgresql.ARRAY(sa.String()), nullable=True))
    op.alter_column('applications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('participants', sa.Column('sporting_disciplines', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'sporting_disciplines')
    op.alter_column('applications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('applications', 'sporting_disciplines')
    op.drop_column('applications', 'country')
    # ### end Alembic commands ###