"""add_scan_logs

Revision ID: 2746eea41709
Revises: 43230a2a6a34
Create Date: 2026-04-04 15:50:41.742376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2746eea41709'
down_revision: Union[str, None] = '43230a2a6a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_logs',
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('scanner_id', sa.UUID(), nullable=False),
    sa.Column('access_granted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['scanner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_logs')
    # ### end Alembic commands ###