"""add extended personal info and specific role to applications

Revision ID: 3f589839d4e8
Revises: b7e6ad63759e
Create Date: 2026-04-17 16:21:43.779468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f589839d4e8'
down_revision: Union[str, None] = 'b7e6ad63759e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('passport_number', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('specific_role', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('emergency_contact_name', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('emergency_contact_phone', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('special_requirements', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'special_requirements')
    op.drop_column('applications', 'emergency_contact_phone')
    op.drop_column('applications', 'emergency_contact_name')
    op.drop_column('applications', 'specific_role')
    op.drop_column('applications', 'passport_number')
    op.drop_column('applications', 'phone_number')
    # ### end Alembic commands ###