"""add host city to tournaments

Revision ID: 877d85aef5bd
Revises: 1d835b96fe09
Create Date: 2026-04-08 12:59:25.286383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877d85aef5bd'
down_revision: Union[str, None] = '1d835b96fe09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('type', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('country', sa.String(), nullable=True))
    
    # 1. Add the column but allow it to be empty temporarily
    op.add_column('tournaments', sa.Column('host_city', sa.String(), nullable=True))
    
    # 2. Give the existing tournament a default city
    op.execute("UPDATE tournaments SET host_city = 'Accra' WHERE host_city IS NULL")
    
    # 3. Now enforce the strict requirement so future tournaments must have a city
    op.alter_column('tournaments', 'host_city', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'host_city')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'type')
    # ### end Alembic commands ###