"""add is_active to tournaments

Revision ID: 920526deb566
Revises: c63e4e6af737
Create Date: 2026-04-09 06:13:17.831257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920526deb566'
down_revision: Union[str, None] = 'c63e4e6af737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'is_active')
    # ### end Alembic commands ###