"""add allowed_categories array to organizations table

Revision ID: b7e6ad63759e
Revises: d85c61c98296
Create Date: 2026-04-17 12:17:41.213326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7e6ad63759e'
down_revision: Union[str, None] = 'd85c61c98296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('allowed_categories', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'allowed_categories')
    # ### end Alembic commands ###