"""add extended frontend fields to zones

Revision ID: b90ef853a23b
Revises: 920526deb566
Create Date: 2026-04-09 08:25:38.467607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90ef853a23b'
down_revision: Union[str, None] = '920526deb566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the columns but allow them to be empty temporarily
    op.add_column('zones', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('zones', sa.Column('code', sa.String(), nullable=True))
    op.add_column('zones', sa.Column('color', sa.String(), nullable=True))
    op.add_column('zones', sa.Column('require_qr_scan', sa.Boolean(), nullable=True))
    
    # 2. Set all existing zones to active and require scans by default
    op.execute("UPDATE zones SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE zones SET require_qr_scan = true WHERE require_qr_scan IS NULL")
    
    # 3. Enforce the strict non-nullable requirements
    op.alter_column('zones', 'is_active', nullable=False)
    op.alter_column('zones', 'require_qr_scan', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'require_qr_scan')
    op.drop_column('zones', 'color')
    op.drop_column('zones', 'code')
    op.drop_column('zones', 'is_active')
    # ### end Alembic commands ###