"""add tournament_id to applications

Revision ID: c63e4e6af737
Revises: 877d85aef5bd
Create Date: 2026-04-08 21:44:39.527770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c63e4e6af737'
down_revision: Union[str, None] = '877d85aef5bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column but allow it to be empty temporarily
    op.add_column('applications', sa.Column('tournament_id', sa.UUID(), nullable=True))
    
    # 2. Link existing applications to the first available tournament in the database
    op.execute("UPDATE applications SET tournament_id = (SELECT id FROM tournaments LIMIT 1) WHERE tournament_id IS NULL")
    
    # 3. Enforce the strict non-nullable requirement
    op.alter_column('applications', 'tournament_id', nullable=False)
    
    # 4. Create the foreign key constraint
    op.create_foreign_key(None, 'applications', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'tournament_id')
    # ### end Alembic commands ###