"""added new accreditation categories across all relevant schemas,

Revision ID: d85c61c98296
Revises: 10185a74f2e7
Create Date: 2026-04-16 15:07:55.903754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime
import uuid


# revision identifiers, used by Alembic.
revision: str = 'd85c61c98296'
down_revision: Union[str, None] = '10185a74f2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Delete old categories from the 'category' table
    old_category_names = [
        "Team Official",
        "Technical and Competition Officials",
        "VIP and Sponsors",
        "Athletes & Team Officials",
        "Technical & Competition Officials",
        "LOC & Workforce",
        "Media & Broadcast",
        "VIPs & Dignitaries",
        "Service Providers"
    ]

    # FIX: Before deleting categories, first delete any ZoneAccess rules that depend on them.
    # This prevents ForeignKeyViolationError.
    escaped_old_names = [name.replace("'", "''") for name in old_category_names]
    old_category_names_sql = ", ".join([f"'{name}'" for name in escaped_old_names])
    op.execute(
        f"DELETE FROM zone_access WHERE category_id IN (SELECT id FROM categories WHERE name IN ({old_category_names_sql}))"
    )

    # Now it's safe to delete the old categories
    for name in old_category_names:
        op.execute(f"DELETE FROM categories WHERE name = '{name.replace(\"'\", \"''\")}'")

    # 2. Add new categories to the 'category' table
    new_categories_to_add = [
        "Coaches",
        "Team Officials",
        "Technical Officials",
        "Medical Staff",
        "VIP/Guests",
        "Volunteer",
        "Transport"
    ]
    conn = op.get_bind()
    existing_categories = [row[0] for row in conn.execute(sa.text("SELECT name FROM categories")).fetchall()]

    for name in new_categories_to_add:
        if name not in existing_categories:
            op.execute(
                sa.text(f"INSERT INTO categories (id, name, created_at) VALUES (:id, :name, :created_at)")
                .bindparams(id=uuid.uuid4(), name=name, created_at=datetime.utcnow())
            )

    # 3. Update existing applications.category values
    op.execute("UPDATE applications SET category = 'Team Officials' WHERE category = 'Team Official'")
    op.execute("UPDATE applications SET category = 'Technical Officials' WHERE category = 'Technical and Competition Officials'")
    op.execute("UPDATE applications SET category = 'VIP/Guests' WHERE category = 'VIP and Sponsors'")
    op.execute("UPDATE applications SET category = 'Athlete' WHERE category = 'Athletes & Team Officials'")
    op.execute("UPDATE applications SET category = 'Technical Officials' WHERE category = 'Technical & Competition Officials'")
    op.execute("UPDATE applications SET category = 'LOC Staff' WHERE category = 'LOC & Workforce'")
    op.execute("UPDATE applications SET category = 'Media' WHERE category = 'Media & Broadcast'")
    op.execute("UPDATE applications SET category = 'VIP/Guests' WHERE category = 'VIPs & Dignitaries'")
    op.execute("UPDATE applications SET category = 'Transport' WHERE category = 'Service Providers'")

    # 4. Update existing participants.role values
    op.execute("UPDATE participants SET role = 'Athlete' WHERE role = 'athletes'")
    op.execute("UPDATE participants SET role = 'Coaches' WHERE role = 'coaches'")
    op.execute("UPDATE participants SET role = 'Team Officials' WHERE role = 'team_managers'")
    op.execute("UPDATE participants SET role = 'Medical Staff' WHERE role = 'medical_personnel'")
    op.execute("UPDATE participants SET role = 'Team Officials' WHERE role = 'NF Officials'")
    op.execute("UPDATE participants SET role = 'Chief Judge' WHERE role = 'Referees & Judges'")
    op.execute("UPDATE participants SET role = 'Event Referee' WHERE role = 'Starter'")
    op.execute("UPDATE participants SET role = 'Event Referee' WHERE role = 'Timekeeper'")
    op.execute("UPDATE participants SET role = 'Competition Director' WHERE role = 'Tech Delegates'")
    op.execute("UPDATE participants SET role = 'Technical Officials' WHERE role = 'Technical & Competition Officials'")
    op.execute("UPDATE participants SET role = 'LOC Staff' WHERE role = 'LOC Members'")
    op.execute("UPDATE participants SET role = 'LOC Staff' WHERE role = 'Accreditation Staff'")
    op.execute("UPDATE participants SET role = 'Volunteer' WHERE role = 'Volunteers'")
    op.execute("UPDATE participants SET role = 'Protocol Volunteers' WHERE role = 'Protocol Officers'")
    op.execute("UPDATE participants SET role = 'Media' WHERE role = 'Written Press'")
    op.execute("UPDATE participants SET role = 'Media' WHERE role = 'Photographers'")
    op.execute("UPDATE participants SET role = 'Media' WHERE role = 'Host Broadcaster'")
    op.execute("UPDATE participants SET role = 'Media' WHERE role = 'Rights Holders'")
    op.execute("UPDATE participants SET role = 'VIP/Guests' WHERE role = 'Government Officials'")
    op.execute("UPDATE participants SET role = 'VIP/Guests' WHERE role = 'CAA Council'")
    op.execute("UPDATE participants SET role = 'VIP/Guests' WHERE role = 'Sponsors'")
    op.execute("UPDATE participants SET role = 'VIP/Guests' WHERE role = 'Invited Guests'")
    op.execute("UPDATE participants SET role = 'Security' WHERE role = 'Security Agencies'")
    op.execute("UPDATE participants SET role = 'Medical Staff' WHERE role = 'Medical Services'")
    op.execute("UPDATE participants SET role = 'LOC Staff' WHERE role = 'IT & Timing'")
    op.execute("UPDATE participants SET role = 'LOC Staff' WHERE role = 'Venue Management'")
    op.execute("UPDATE participants SET role = 'Athlete' WHERE role = 'Athletes & Team Officials'")
    op.execute("UPDATE participants SET role = 'Technical Officials' WHERE role = 'Technical & Competition Officials'")
    op.execute("UPDATE participants SET role = 'LOC Staff' WHERE role = 'LOC & Workforce'")
    op.execute("UPDATE participants SET role = 'Media' WHERE role = 'Media & Broadcast'")
    op.execute("UPDATE participants SET role = 'VIP/Guests' WHERE role = 'VIPs & Dignitaries'")
    op.execute("UPDATE participants SET role = 'Transport Staff' WHERE role = 'Service Providers'")
    op.execute("UPDATE participants SET role = 'Transport Staff' WHERE role = 'Transport'")
    op.execute("UPDATE participants SET role = 'Volunteer' WHERE role = 'Volunteer'")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert participants.role
    op.execute("UPDATE participants SET role = 'athletes' WHERE role = 'Athlete'")
    op.execute("UPDATE participants SET role = 'coaches' WHERE role = 'Coaches'")
    op.execute("UPDATE participants SET role = 'team_managers' WHERE role = 'Team Officials'")
    op.execute("UPDATE participants SET role = 'medical_personnel' WHERE role = 'Medical Staff'")
    op.execute("UPDATE participants SET role = 'Referees & Judges' WHERE role = 'Chief Judge'")
    op.execute("UPDATE participants SET role = 'Starter' WHERE role = 'Event Referee'")
    op.execute("UPDATE participants SET role = 'Tech Delegates' WHERE role = 'Competition Director'")
    op.execute("UPDATE participants SET role = 'Technical & Competition Officials' WHERE role = 'Technical Officials'")
    op.execute("UPDATE participants SET role = 'LOC Members' WHERE role = 'LOC Staff'")
    op.execute("UPDATE participants SET role = 'Volunteers' WHERE role = 'Volunteer'")
    op.execute("UPDATE participants SET role = 'Protocol Officers' WHERE role = 'Protocol Volunteers'")
    op.execute("UPDATE participants SET role = 'Government Officials' WHERE role = 'VIP/Guests'")
    op.execute("UPDATE participants SET role = 'Security Agencies' WHERE role = 'Security'")
    op.execute("UPDATE participants SET role = 'Medical Services' WHERE role = 'Medical Staff'")
    op.execute("UPDATE participants SET role = 'Service Providers' WHERE role = 'Transport Staff'")

    # Revert applications.category
    op.execute("UPDATE applications SET category = 'Team Official' WHERE category = 'Team Officials'")
    op.execute("UPDATE applications SET category = 'Technical and Competition Officials' WHERE category = 'Technical Officials'")
    op.execute("UPDATE applications SET category = 'VIP and Sponsors' WHERE category = 'VIP/Guests'")
    op.execute("UPDATE applications SET category = 'Athletes & Team Officials' WHERE category = 'Athlete'")
    op.execute("UPDATE applications SET category = 'LOC & Workforce' WHERE category = 'LOC Staff'")
    op.execute("UPDATE applications SET category = 'Media & Broadcast' WHERE category = 'Media'")
    op.execute("UPDATE applications SET category = 'VIPs & Dignitaries' WHERE category = 'VIP/Guests'")
    op.execute("UPDATE applications SET category = 'Service Providers' WHERE category = 'Transport'")

    # Re-add old categories
    old_category_names_to_readd = [
        "Team Official", "Technical and Competition Officials", "VIP and Sponsors",
        "Athletes & Team Officials", "Technical & Competition Officials", "LOC & Workforce",
        "Media & Broadcast", "VIPs & Dignitaries", "Service Providers"
    ]
    for name in old_category_names_to_readd:
        op.execute(
            sa.text(f"INSERT INTO categories (id, name, created_at) VALUES (:id, :name, :created_at)")
            .bindparams(id=uuid.uuid4(), name=name, created_at=datetime.utcnow())
        )

    # Delete new categories
    new_category_names_to_delete = [
        "Coaches", "Team Officials", "Technical Officials", "Medical Staff", "VIP/Guests", "Volunteer", "Transport"
    ]

    # FIX: Add the same safety check to the downgrade path.
    escaped_new_names = [name.replace("'", "''") for name in new_category_names_to_delete]
    new_category_names_sql = ", ".join([f"'{name}'" for name in escaped_new_names])
    op.execute(
        f"DELETE FROM zone_access WHERE category_id IN (SELECT id FROM categories WHERE name IN ({new_category_names_sql}))"
    )

    for name in new_category_names_to_delete:
        op.execute(f"DELETE FROM categories WHERE name = '{name.replace(\"'\", \"''\")}'")
    # ### end Alembic commands ###