"""add performance indexes to core tables

Revision ID: eb45fc6d7341
Revises: 3f589839d4e8
Create Date: 2026-04-20 15:02:39.117536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb45fc6d7341'
down_revision: Union[str, None] = '3f589839d4e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_category'), 'applications', ['category'], unique=False)
    op.create_index(op.f('ix_applications_organization_id'), 'applications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_submitted_at'), 'applications', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_applications_tournament_id'), 'applications', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index(op.f('ix_documents_application_id'), 'documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_participants_application_id'), 'participants', ['application_id'], unique=False)
    op.create_index(op.f('ix_participants_category_id'), 'participants', ['category_id'], unique=False)
    op.create_index(op.f('ix_participants_organization_id'), 'participants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_participants_role'), 'participants', ['role'], unique=False)
    op.create_index(op.f('ix_participants_tournament_id'), 'participants', ['tournament_id'], unique=False)
    op.add_column('scan_logs', sa.Column('direction', sa.String(length=3), nullable=False))
    op.create_index(op.f('ix_scan_logs_access_granted'), 'scan_logs', ['access_granted'], unique=False)
    op.create_index(op.f('ix_scan_logs_created_at'), 'scan_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_logs_participant_id'), 'scan_logs', ['participant_id'], unique=False)
    op.create_index(op.f('ix_scan_logs_scanner_id'), 'scan_logs', ['scanner_id'], unique=False)
    op.create_index(op.f('ix_scan_logs_zone_id'), 'scan_logs', ['zone_id'], unique=False)
    op.create_index(op.f('ix_zone_access_category_id'), 'zone_access', ['category_id'], unique=False)
    op.create_index(op.f('ix_zone_access_zone_id'), 'zone_access', ['zone_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_access_zone_id'), table_name='zone_access')
    op.drop_index(op.f('ix_zone_access_category_id'), table_name='zone_access')
    op.drop_index(op.f('ix_scan_logs_zone_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_scanner_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_participant_id'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_created_at'), table_name='scan_logs')
    op.drop_index(op.f('ix_scan_logs_access_granted'), table_name='scan_logs')
    op.drop_column('scan_logs', 'direction')
    op.drop_index(op.f('ix_participants_tournament_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_role'), table_name='participants')
    op.drop_index(op.f('ix_participants_organization_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_category_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_application_id'), table_name='participants')
    op.drop_index(op.f('ix_documents_application_id'), table_name='documents')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_tournament_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_submitted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_organization_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_category'), table_name='applications')
    # ### end Alembic commands ###