name: Build and Push to AWS ECR

on:
  push:
    branches: [ "main" ]

env:
  # Suppresses the Node.js 20 deprecation warning
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  AWS_REGION: eu-north-1
  ECR_API_REPOSITORY: ams-fastapi
  ECR_CELERY_REPOSITORY: ams-celery
  ECS_CLUSTER: ams-cluster                  # Replace with your actual ECS Cluster name
  ECS_API_SERVICE: ams-fastapi-task-service-2dlnwx6b
  ECS_CELERY_SERVICE: ams-celery-service
  ECS_CELERY_BEAT_SERVICE: ams-celery-beat-task-service-nq9j101c

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build the Docker image once
        docker build -t app-image:$IMAGE_TAG .
        
        # Tag and Push to the FastAPI repository
        docker tag app-image:$IMAGE_TAG $ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG
        docker tag app-image:$IMAGE_TAG $ECR_REGISTRY/$ECR_API_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_API_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_API_REPOSITORY:latest
        
        # Tag and Push to the Celery repository
        docker tag app-image:$IMAGE_TAG $ECR_REGISTRY/$ECR_CELERY_REPOSITORY:$IMAGE_TAG
        docker tag app-image:$IMAGE_TAG $ECR_REGISTRY/$ECR_CELERY_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_CELERY_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_CELERY_REPOSITORY:latest
        
    - name: Force ECS services to deploy new image
      run: |
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_API_SERVICE }} --force-new-deployment
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_CELERY_SERVICE }} --force-new-deployment
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_CELERY_BEAT_SERVICE }} --force-new-deployment