ORG_ALLOWED_CATEGORIES = {
    "Team Algeria": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Angola": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Benin": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Botswana": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Burkina Faso": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Burundi": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Cabo Verde": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Cameroon": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Central African Republic": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Chad": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Comoros": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Congo": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Congo (DRC)": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Côte d'Ivoire": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Djibouti": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Egypt": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Equatorial Guinea": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Eritrea": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Eswatini": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Ethiopia": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Gabon": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Gambia": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Ghana": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Guinea": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Guinea-Bissau": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Kenya": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Lesotho": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Liberia": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Libya": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Madagascar": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Malawi": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Mali": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Mauritania": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Mauritius": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Morocco": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Mozambique": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Namibia": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Niger": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Nigeria": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Rwanda": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team São Tomé and Príncipe": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Senegal": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Seychelles": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Sierra Leone": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Somalia": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team South Africa": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team South Sudan": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Sudan": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Tanzania": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Togo": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Tunisia": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Uganda": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Zambia": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "Team Zimbabwe": ["Athletes & Team Officials", "VIPs & Dignitaries"],
    "LOC Staff": ["LOC & Workforce", "VIPs & Dignitaries", "Service Providers"],
    "Media": ["Media & Broadcast"],
    "International Technical Official": ["Technical & Competition Officials"],
    "Ghana Athletics Association": ["Technical & Competition Officials", "VIPs & Dignitaries"],
    "Volunteer": ["LOC & Workforce"],
    "Service Staff": ["Service Providers"],
    "VIP/Guest": ["VIPs & Dignitaries"],
    "Confederation of African Athletics": ["Technical & Competition Officials", "VIPs & Dignitaries"],
    "World Athletics": ["Technical & Competition Officials", "VIPs & Dignitaries"]
}