ORG_ALLOWED_CATEGORIES = {
    "Team Algeria": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Angola": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Benin": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Botswana": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Burkina Faso": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Burundi": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Cabo Verde": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Cameroon": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Central African Republic": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Chad": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Comoros": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Congo": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Congo (DRC)": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Côte d'Ivoire": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Djibouti": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Egypt": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Equatorial Guinea": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Eritrea": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Eswatini": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Ethiopia": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Gabon": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Gambia": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Ghana": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Guinea": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Guinea-Bissau": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Kenya": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Lesotho": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Liberia": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Libya": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Madagascar": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Malawi": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Mali": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Mauritania": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Mauritius": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Morocco": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Mozambique": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Namibia": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Niger": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Nigeria": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Rwanda": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team São Tomé and Príncipe": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Senegal": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Seychelles": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Sierra Leone": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Somalia": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team South Africa": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team South Sudan": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Sudan": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Tanzania": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Togo": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Tunisia": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Uganda": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Zambia": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "Team Zimbabwe": ["Athlete", "Coaches", "Team Officials", "Medical Staff", "VIP/Guests"],
    "LOC Staff": ["LOC Staff", "Volunteer", "Security", "Transport", "VIP/Guests"],
    "Media": ["Media"],
    "International Technical Official": ["Technical Officials"],
    "Ghana Athletics Association": ["Technical Officials", "VIP/Guests"],
    "Volunteer": ["Volunteer"],
    "Service Staff": ["Security", "Transport", "LOC Staff"],
    "VIP/Guest": ["VIP/Guests"],
    "Confederation of African Athletics": ["Technical Officials", "VIP/Guests"],
    "World Athletics": ["Technical Officials", "VIP/Guests"]
}

SEEDED_ORGANIZATIONS = [
    "Team Algeria", "Team Angola", "Team Benin", "Team Botswana", "Team Burkina Faso",
    "Team Burundi", "Team Cabo Verde", "Team Cameroon", "Team Central African Republic",
    "Team Chad", "Team Comoros", "Team Congo", "Team Congo (DRC)", "Team Côte d'Ivoire",
    "Team Djibouti", "Team Egypt", "Team Equatorial Guinea", "Team Eritrea", "Team Eswatini",
    "Team Ethiopia", "Team Gabon", "Team Gambia", "Team Ghana", "Team Guinea",
    "Team Guinea-Bissau", "Team Kenya", "Team Lesotho", "Team Liberia", "Team Libya",
    "Team Madagascar", "Team Malawi", "Team Mali", "Team Mauritania", "Team Mauritius",
    "Team Morocco", "Team Mozambique", "Team Namibia", "Team Niger", "Team Nigeria",
    "Team Rwanda", "Team São Tomé and Príncipe", "Team Senegal", "Team Seychelles",
    "Team Sierra Leone", "Team Somalia", "Team South Africa", "Team South Sudan",
    "Team Sudan", "Team Tanzania", "Team Togo", "Team Tunisia", "Team Uganda",
    "Team Zambia", "Team Zimbabwe", "LOC Staff", "Media", "International Technical Official",
    "Ghana Athletics Association", "Volunteer", "Service Staff", "VIP/Guest",
    "Confederation of African Athletics", "World Athletics"
]